import { Specs } from '../registry.mjs';
import { Animal } from './classes/animal.mjs';
import { Dog } from './classes/dog.mjs';
import { Fur } from './classes/fur.mjs';
import { ID_TypeRegister } from './classes/id-type-register.mjs';
import { TestTypeRegister } from './classes/test-type-register.mjs';
import { TestTypeMemberDecorator } from './classes/test-type-member-decorator.mjs';
export { Animal, Dog, ID_TypeRegister, TestTypeRegister,  TestTypeMemberDecorator, Fur };
const specs = new Specs(60000, './');
specs.run();